### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by muskansingh65553** [jvsteiner/shadowsocks-deploy#2]
Hello sir
I am unable to setup the script in my server
please help me 
i change the path of pem file and give proper permission also

![image](https://user-images.githubusercontent.com/71725061/183430238-cdd46b9f-24e6-402d-9565-8759277d6557.png)

**Comment by muskansingh65553** [comment]
![image](https://user-images.githubusercontent.com/71725061/183430303-c1afe83d-6899-4206-bed0-e392aa457d06.png)

**Comment by jvsteiner** [comment]
Seems these errors result from your environment - I cant help.
